# Generated by Django 4.1.5 on 2023-01-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('cofirmpassword', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
