# Generated by Django 4.1.5 on 2023-01-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerinfo',
            old_name='cofirmpassword',
            new_name='confirmpassword',
        ),
    ]
