# Generated by Django 4.1.5 on 2023-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_cofirmpassword_registerinfo_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_question', models.CharField(max_length=100)),
                ('textarea_answer', models.TextField()),
            ],
        ),
    ]
