# Generated by Django 4.1.5 on 2023-02-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='mcq_question',
        ),
    ]
