# Generated by Django 4.1.5 on 2023-02-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_formsubmission_mcq_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
