# Generated by Django 4.1.5 on 2023-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_formsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registerinfo',
        ),
    ]
